services:
  db:
    image: postgres
    container_name: postgresql
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 120
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: ai_search_service
      DB_USER: postgres
      DB_PASS: 1
