services:
  db:
    image: postgres
    container_name: postgresql
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 120
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: ai_search_service
      DB_USER: postgres
      DB_PASS: 1

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"
    expose:
      - 6379

  api:
    container_name: ai-file-search-service
    build: .
    ports:
      - "3000:3000"
    expose:
      - 3000
    environment:
      DB_URL: postgresql+psycopg2://postgres:1@db:5432/ai_search_service
      REDIS_HOST: redis

      # Set values
      GOOGLE_APPLICATION_CREDENTIALS: "credentials.json"
      PINECONE_API_KEY:
      OPENAI_API_KEY:
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
