name: AI File Search Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  SCA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==24.8.0 isort==5.13.2 flake8==7.1.1 mypy==1.11.2
      - name: Lint with flake8
        run: |
          flake8 .  --statistics
      - name: Typehint with mypy
        run: |
          mypy .
      - name: Check formatting
        run: black . --check
      - name: Check isort imports
        run: |
          isort . --check-only --profile=black